'use strict';

const EVENT_LABELS = {
  unmatched_unit: 'Unmatched Unit',
  undeclared_support_gap: 'Undeclared Support Gap',
  reviewer_confirmed_contradiction: 'Reviewer-Confirmed Contradiction',
  declared_role_divergence: 'Declared Role Divergence',
  divergent_evidence_basis: 'Divergent Evidence Basis',
  divergent_interpretation: 'Divergent Interpretation',
  confidence_divergence: 'Confidence Divergence',
  dependency_divergence: 'Dependency Divergence',
  convergent_conclusion_different_path: 'Convergent Conclusion, Different Declared Path',
  divergent_conclusion_shared_evidence: 'Divergent Conclusion, Shared Evidence',
  evidence_used_one_side_only: 'Evidence Used by One Side Only',
};

export function toMarkdown(result) {
  const L = [];
  L.push(`# Observed Divergence Report`);
  L.push('');
  L.push(`**Case:** ${result.case_id}  `);
  L.push(`**Question:** ${result.question}  `);
  L.push(`**Path A:** ${result.path_a} (analyst ${result.analyst_a})  `);
  L.push(`**Path B:** ${result.path_b} (analyst ${result.analyst_b})  `);
  L.push(`**Engine version:** ${result.engine_version}`);
  L.push('');
  L.push('## Metrics');
  L.push('');
  L.push('| Metric | Value |');
  L.push('|---|---|');
  for (const [k, v] of Object.entries(result.metrics)) {
    const cell = (v && typeof v === 'object' && 'value' in v)
      ? (v.value == null ? `n/a — ${v.note}` : v.value)
      : v;
    L.push(`| ${k} | ${cell} |`);
  }
  L.push('');
  L.push('## Observed Divergence Events');
  L.push('');
  if (!result.events.length) L.push('_No events were generated._');
  for (const e of result.events) {
    L.push(`### ${EVENT_LABELS[e.kind] || e.kind}`);
    L.push(`_id: \`${e.id}\`_`);
    if (e.a) L.push(`- **A (${e.a.type}, ${e.a.id}):** ${e.a.text}`);
    if (e.b) L.push(`- **B (${e.b.type}, ${e.b.id}):** ${e.b.text}`);
    if (e.reviewer_decision) L.push(`- **Reviewer decision:** ${e.reviewer_decision.decision}${e.reviewer_decision.relation ? ` (${e.reviewer_decision.relation})` : ''}`);
    for (const [k, v] of Object.entries(e.details || {})) {
      if (v == null || (Array.isArray(v) && !v.length)) continue;
      L.push(`- **${k}:** ${Array.isArray(v) ? v.join(', ') : v}`);
    }
    L.push('');
  }
  L.push('## Evidence Usage');
  L.push('');
  L.push('| Evidence | Status | A units | B units |');
  L.push('|---|---|---|---|');
  for (const e of result.evidence_usage) L.push(`| ${e.id} | ${e.status} | ${e.a_units.join(', ')} | ${e.b_units.join(', ')} |`);
  L.push('');
  L.push('---');
  L.push('Generated by Reasoning Diff Lab. This report lists observed structural divergences that a reviewer confirmed. It does not determine truth, rank analysts, or prove that the comparison method itself is useful — that is the open empirical question this instrument is built to test (see docs/EXPERIMENT_PROTOCOL.md).');
  return L.join('\n');
}

export function toCsv(result) {
  const header = ['event_id', 'kind', 'case_id', 'path_a', 'path_b', 'unit_a', 'unit_b', 'reviewer_decision', 'relation'];
  const rows = result.events.map(e => [
    e.id, e.kind, result.case_id, result.path_a, result.path_b,
    e.a?.id || '', e.b?.id || '', e.reviewer_decision?.decision || '', e.reviewer_decision?.relation || '',
  ]);
  return [header, ...rows].map(r => r.map(csvCell).join(',')).join('\n');
}

function csvCell(v) {
  const s = String(v ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
